### ISSUE TITLE
Suite name missing

### ISSUE THREAD

**Issue by sprat** [bySabi/karma-tap#13]
I filed an issue in karma-tap-reporter because the suite name never appear in the output of the tool (https://github.com/fumiakiy/karma-tap-reporter/issues/11). However, it seems that the problem is in karma-tap, as the `suite` array is always empty. I'll have a look if I can find some time, but if someone know how to fix that, your comments/PR are welcome ;)

**Comment by tmcw** [comment]
This repository is 'up for adoption': I no longer use or maintain this module, and will transfer it to any prospective maintainer.

**Comment by sprat** [comment]
Ok, I am not willing to maintain this library, sorry. I'm just trying to get my project done and it's harder than I thought.

**Comment by unional** [comment]
@tmcw I'm considering adapting this repo because I want to use it for my company (unless karma-ava comes out in time, but unlikely).

I want to learn a bit more about it so that I know I can actually handle it afterwards.

Here is a question regarding `suite`:
https://github.com/tmcw-up-for-adoption/karma-tap/blob/master/src/adapter.js#L19

Where does this result object interface defined? I can't find it on TAP. I saw that you specify it (although it is empty) and `karma-tap-reporter` is using it (hence this issue).

**Comment by bySabi** [comment]
this is solved now with pending PR´s:
- https://github.com/fumiakiy/karma-tap-reporter/pull/12
- https://github.com/tmcw-up-for-adoption/karma-tap/pull/15

**Comment by bySabi** [comment]
Solved on current release `2.1.3`
